truncate table ETL_STAGGING.STG_F_WEATHER_TEMP;
truncate table ETL_STAGGING.STG_F_WEATHER;

--------------------------------------------------------
--  DDL for Table STG_F_WEATHER_TEMP
--------------------------------------------------------
drop table stg_f_weather_temp;

  CREATE TABLE ETL_STAGGING.STG_F_WEATHER_TEMP (	
   STATION_ID VARCHAR2(50)
	,WDATE VARCHAR2(50)
	,WELEMENT VARCHAR2(50) 
	,DATA_VALUE VARCHAR2(50)
	,M_FLAG VARCHAR2(1)
	,Q_FLAG VARCHAR2(1)
	,S_FLAG VARCHAR2(1)
	,OBS_TIME VARCHAR2(50)
	,WYEAR NUMBER
   );
   
--------------------------------------------------------
--  DDL for Table STG_F_WEATHER
--------------------------------------------------------
drop table ETL_STAGGING.STG_F_WEATHER;

  CREATE TABLE ETL_STAGGING.STG_F_WEATHER (	
   DWH_SOURCE_KEY VARCHAR2(50)
  ,DWH_DELETE_FLAG VARCHAR2(1)
  ,DWH_INSERT_FLAG VARCHAR2(1)
  ,DWH_VALID_FROM DATE
  ,STATION_ID VARCHAR2(50)
	,WDATE VARCHAR2(50)
	,WELEMENT VARCHAR2(50) 
	,DATA_VALUE VARCHAR2(50)
	,M_FLAG VARCHAR2(1)
	,Q_FLAG VARCHAR2(1)
	,S_FLAG VARCHAR2(1)
	,OBS_TIME VARCHAR2(50)
	,WYEAR NUMBER
   );
   

 
CREATE INDEX "STG_F_WEATHER_TEMP_IDX" ON STG_F_WEATHER_TEMP ("DWH_SOURCE_KEY");
CREATE INDEX "STG_F_WEATHER_IDX" ON STG_F_WEATHER ("DWH_SOURCE_KEY");
DROP INDEX STG_F_WEATHER_TEMP_IDX;

   