truncate table ETL_STAGGING.STG_D_STATIONS_TEMP;
truncate table ETL_STAGGING.STG_D_STATIONS;

--------------------------------------------------------
--  Table STG_D_STATIONS_TEMP 
--------------------------------------------------------
DROP TABLE ETL_STAGGING.STG_D_STATIONS_TEMP  ;

CREATE TABLE ETL_STAGGING.STG_D_STATIONS_TEMP (  
ID VARCHAR2(11), 
LATITUDE VARCHAR2(10), 
LONGITUDE VARCHAR2(15), 
ELEVATION VARCHAR2(15), 
STATE VARCHAR2(2), 
NAME VARCHAR2(30), 
GSNFLAG VARCHAR2(3), 
HCNFLAG VARCHAR2(3), 
WMOID VARCHAR2(5)
);

--------------------------------------------------------
--  Table STG_D_STATIONS
--------------------------------------------------------
DROP TABLE ETL_STAGGING.STG_D_STATIONS;

CREATE TABLE ETL_STAGGING.STG_D_STATIONS (	
DWH_SOURCE_KEY VARCHAR2(50)
,DWH_DELETE_FLAG VARCHAR2(1)
,DWH_INSERT_FLAG VARCHAR2(1)
,DWH_VALID_FROM DATE
,ID VARCHAR2(11)
,LATITUDE VARCHAR2(15)
,LONGITUDE VARCHAR2(15)
,ELEVATION VARCHAR2(10)
,STATE_CODE VARCHAR2(2)
,STATE_NAME VARCHAR2(30)
,NAME VARCHAR2(30) 
,GSNFLAG VARCHAR2(3)
,HCNFLAG VARCHAR2(3)
,WMOID VARCHAR2(5)
) ;