truncate table ETL_STAGGING.STG_D_PLANE_DATA_TEMP;
truncate table ETL_STAGGING.STG_D_PLANE_DATA;

--------------------------------------------------------
--  Table D_PLANE_DATA_SKEY_TEMP - 
--------------------------------------------------------
DROP TABLE ETL_STAGGING.STG_D_PLANE_DATA_TEMP ;

CREATE TABLE ETL_STAGGING.STG_D_PLANE_DATA_TEMP (  
   TAILNUM VARCHAR2(20)
  ,TYPE VARCHAR2(20)
  ,MANUFACTURER VARCHAR2(30)
  ,ISSUE_DATE VARCHAR2(10)
  ,MODEL VARCHAR2(20)
  ,STATUS VARCHAR2(20)
  ,AIRCRAFT_TYPE VARCHAR2(30)
  ,ENGINE_TYPE VARCHAR2(20)
  ,YEAR VARCHAR2(4)
 );
 
 
 
-----------------------------------------------------------------
--    STG_D_PLANE_DATA
-----------------------------------------------------------------
DROP TABLE ETL_STAGGING.STG_D_PLANE_DATA;

CREATE TABLE ETL_STAGGING.STG_D_PLANE_DATA (	
   DWH_SOURCE_KEY VARCHAR2(50)
  ,DWH_DELETE_FLAG VARCHAR2(1)
  ,DWH_INSERT_FLAG VARCHAR2(1)
  ,DWH_VALID_FROM DATE
  ,YEAR VARCHAR2(4)
  ,ENGINE_TYPE VARCHAR2(20)
  ,AIRCRAFT_TYPE VARCHAR2(30)
  ,STATUS VARCHAR2(20)
  ,MODEL VARCHAR2(20)
  ,ISSUE_DATE VARCHAR2(10)
  ,MANUFACTURER VARCHAR2(30)
  ,TYPE VARCHAR2(20)
  ,TAILNUM VARCHAR2(20)
);
