CREATE UNIQUE INDEX "SOURCE"."STAT_ID_UNIQUE_IDX" ON "SOURCE"."D_STATIONS" ("ID") 
TABLESPACE "SOURCE" ;
CREATE BITMAP INDEX "SOURCE"."STAT_STATE_BITMAP_IDX" ON "SOURCE"."D_STATIONS" ("STATE") 
TABLESPACE "SOURCE" ;

CREATE BITMAP INDEX "SOURCE"."FL_UNIQUECARRIER_BITMAP_IDX" ON "SOURCE"."F_FLIGHTS" ("UNIQUECARRIER") 
TABLESPACE "SOURCE" ;
CREATE BITMAP INDEX "SOURCE"."FL_ORIGIN_BITMAP_IDX" ON "SOURCE"."F_FLIGHTS" ("ORIGIN") 
TABLESPACE "SOURCE" ;
CREATE BITMAP INDEX "SOURCE"."FL_DEST_BITMAP_IDX" ON "SOURCE"."F_FLIGHTS" ("DEST") 
TABLESPACE "SOURCE" ;
CREATE BITMAP INDEX "SOURCE"."FL_YEAR_BITMAP_IDX" ON "SOURCE"."F_FLIGHTS" ("YEAR") 
TABLESPACE "SOURCE" ;
CREATE BITMAP INDEX "SOURCE"."FL_TAILNUM_BITMAP_IDX" ON "SOURCE"."F_FLIGHTS" ("TAILNUM") 
TABLESPACE "SOURCE" ;

CREATE INDEX "SOURCE"."W_STATION_ID_IDX" ON "SOURCE"."F_WEATHER" ("STATION_ID") 
TABLESPACE "SOURCE" ;
CREATE INDEX "SOURCE"."W_DATE_IDX" ON "SOURCE"."F_WEATHER" ("DATE") 
TABLESPACE "SOURCE" ;

CREATE BITMAP INDEX "SOURCE"."WE_YEAR_BITMAP_IDX" ON "SOURCE"."F_WEATHER" ("YEAR") 
TABLESPACE "SOURCE" ;





